# Generated by Django 4.2.3 on 2023-08-05 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='approvedby',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='deansign',
            field=models.ImageField(blank=True, default='../media/users/img.png', null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='debit_head',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='dept',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='estcost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='expert1Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='expert2Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='facsign',
            field=models.ImageField(blank=True, default='../media/users/img.png', null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='hodsign',
            field=models.ImageField(blank=True, default='../media/users/img.png', null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='item_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='refno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to=settings.AUTH_USER_MODEL),
        ),
    ]
