# Generated by Django 4.2.3 on 2023-08-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_alter_userdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='deansign',
            field=models.ImageField(blank=True, default='../media/users/img.jpg', null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='facsign',
            field=models.ImageField(blank=True, default='../media/users/img.jpg', null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='hodsign',
            field=models.ImageField(blank=True, default='../media/users/img.jpg', null=True, upload_to='users/'),
        ),
    ]
