# Generated by Django 4.2.3 on 2023-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_alter_userdata_deansign_alter_userdata_facsign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='facsign',
            field=models.ImageField(default='../media/users/img.jpg', upload_to='users/'),
        ),
    ]
