# Generated by Django 4.2.3 on 2023-08-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_alter_userdata_facsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='refno2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
