# Generated by Django 4.2.3 on 2023-08-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0010_userdata_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='listnadd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='suppliers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
