# Generated by Django 4.2.3 on 2023-08-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0013_userdata_date4q_userdata_notino'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='name_goods',
            field=models.TextField(blank=True, null=True),
        ),
    ]
