# Generated by Django 4.2.3 on 2023-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0014_userdata_name_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='datebid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='estamt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='timesupply',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
