# Generated by Django 4.2.3 on 2023-08-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0015_userdata_datebid_userdata_estamt_userdata_timesupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='addbid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
