# Generated by Django 4.2.3 on 2023-08-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0018_userdata_date5_userdata_refno5'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bidaccnames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='bidaccno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='bidno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='bidrejnames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='bidrejno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='bidrepno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='date6',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='datefinbid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='refno6',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
