# Generated by Django 4.2.3 on 2023-09-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0019_userdata_bidaccnames_userdata_bidaccno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='date7',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='date9',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='refno7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='refno9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
