from django.db import models
from django.contrib.auth.models import User

class UserData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)    
    refno = models.IntegerField(null=True, blank=True)
    refno2 = models.IntegerField(null=True, blank=True)
    refno5 = models.IntegerField(null=True, blank=True)
    refno6 = models.IntegerField(null=True, blank=True)
    refno7 = models.IntegerField(null=True, blank=True)
    refno9 = models.IntegerField(null=True, blank=True)
    date = models.DateTimeField(null=True, blank=True)
    date2 = models.DateTimeField(null=True, blank=True)
    date5 = models.DateTimeField(null=True, blank=True)
    date6 = models.DateTimeField(null=True, blank=True)
    date7 = models.DateTimeField(null=True, blank=True)
    date9 = models.DateTimeField(null=True, blank=True)
    date4q = models.DateTimeField(null=True, blank=True)
    datebid = models.DateTimeField(null=True, blank=True)
    datefinbid = models.DateTimeField(null=True, blank=True)
    dept = models.TextField(null=True, blank=True)
    name_goods = models.TextField(null=True, blank=True)
    addbid = models.TextField(null=True, blank=True)
    item_proc=models.TextField(null=True, blank=True)
    spec=models.TextField(null=True, blank=True)
    curr=models.TextField(null=True, blank=True)
    tax_dut=models.TextField(null=True, blank=True)
    other_charges=models.TextField(null=True, blank=True)
    name_add_firm=models.TextField(null=True, blank=True)
    name_add_auth=models.TextField(null=True, blank=True)
    name_des_bid=models.TextField(null=True, blank=True)
    bus_add=models.TextField(null=True, blank=True)
    quantity_doc4q=models.TextField(null=True, blank=True)
    details=models.TextField(null=True, blank=True)
    notino=models.TextField(null=True, blank=True)
    debit_head = models.TextField(null=True, blank=True)
    item_name= models.TextField(null=True, blank=True)
    type= models.TextField(null=True, blank=True)
    quantity=models.IntegerField(null=True, blank=True)
    warranty_doc4q=models.IntegerField(null=True, blank=True)
    del_sched=models.IntegerField(null=True, blank=True)
    estcost=models.IntegerField(null=True, blank=True)
    estamt=models.IntegerField(null=True, blank=True)
    warranty=models.IntegerField(null=True, blank=True)
    timesupply=models.IntegerField(null=True, blank=True)
    expert1Name= models.TextField(null=True, blank=True)
    expert2Name= models.TextField(null=True, blank=True)
    listnadd=models.TextField(null=True, blank=True)
    suppliers=models.TextField(null=True, blank=True)
    venue= models.TextField(null=True, blank=True)
    bidaccnames= models.TextField(null=True, blank=True)
    bidrejnames= models.TextField(null=True, blank=True)
    bidno= models.IntegerField(null=True, blank=True)
    bidaccno= models.IntegerField(null=True, blank=True)
    bidrejno= models.IntegerField(null=True, blank=True)
    bidrepno= models.IntegerField(null=True, blank=True)
    approvedby= models.TextField(null=True, blank=True)
    facsign=models.ImageField( default="../media/users/img.jpg" , upload_to='users/')
    addsheet=models.FileField(upload_to='users/addsheets/', null=True, blank=True)
    hodsign=models.ImageField( default="../media/users/img.jpg", null=True, blank=True, upload_to='users/')
    deansign=models.ImageField( default="../media/users/img.jpg", null=True, blank=True, upload_to='users/')
    # Add other fields as needed
    def __str__(self):
        return f"{self.user.username} - {self.refno}"